# justfile — generated by justx · the justfile companion
# https://github.com/amberpixels/just-x
#
# Blocks between `# >>> justx:<id>` and `# <<< justx:<id>` are managed by justx.
# Edit anything outside the fences freely; `j @upgrade` (v2) re-syncs managed blocks.

# standardgo carries the ruleset and the golangci-lint engine in one binary, so this
# repo holds no lint config of its own. It is invoked with `go run` rather than a
# go.mod tool directive on purpose: standardgo requires lostfield and golangci-lint,
# and lostfield is meant to be required *by* golangci-lint upstream, so the directive
# would put a copy of golangci-lint (and of lostfield itself) in this module's graph.
# The fmt/lint/fix fences are removed for the same reason - they must not resync.
standardgo := "github.com/amberpixels/standardgo/cmd/standardgo@v0.1.2"

# The floor this library promises to support. Keep in sync with the `go` directive
# in go.mod - that is the number consumers actually see. CI passes FLOOR_GO=local,
# having already installed the floor toolchain, so it never downloads a second one.
floor_go := env("FLOOR_GO", "go1.25.0")

export PATH := env("PATH") + ":" + `go env GOPATH` + "/bin"
binary_name := "lostfield"
install_path := `go env GOPATH` + "/bin"

# Default recipe: format (rewrites, decides nothing; `just fix` is the mutable one)
default: fmt

# format Go code - rewrites to canonical form
fmt:
    go run {{ standardgo }} fmt ./...

# lint Go code - reports findings, changes nothing
lint:
    go run {{ standardgo }} ./...

# auto-fix what can be fixed - run on a clean tree and read the diff
fix:
    go run {{ standardgo }} ./... --fix

# >>> justx:test (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run tests
test:
    go test ./...
# <<< justx:test

# >>> justx:build (managed) — `j @upgrade` re-syncs; remove these fences to take over
# build
build:
    go build ./...
# <<< justx:build

# check that the go.mod floor still builds and vets, standalone. vet is the leg that
# matters: too-new stdlib APIs compile fine and only stdversion reports them.
floor:
    GOWORK=off GOTOOLCHAIN={{ floor_go }} go build ./...
    GOWORK=off GOTOOLCHAIN={{ floor_go }} go vet ./...

# run all checks - read-only, safe for CI
ci: lint test floor

# Install the linter binary to GOPATH/bin
install:
    @echo "Installing {{ binary_name }} to {{ install_path }}..."
    @go install ./cmd/lostfield
    @echo "✓ {{ binary_name }} installed successfully"
    @echo "You can now run 'go vet -vettool=$(which {{ binary_name }}) ./...' in any Go project"

# Run the linter on a specified path (usage: just run [TARGET=path])
run TARGET=".":
    @cd {{ TARGET }} && go vet -vettool=$(which {{ binary_name }}) ./... || true
